name: lotus_erp
description: A new Flutter project.

publish_to: "none" 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  community_material_icon: ^5.9.55
  shared_preferences: ^0.5.7
  get:
  http: any
  jiffy: ^4.1.0
  asuka: any
  flutter_barcode_scanner: ^2.0.0
  path_provider: ^2.0.2
  image_picker: ^0.8.2
  cupertino_icons: ^1.0.2
  mobx: ^2.0.1
  flutter_mobx:
  http_parser: ^4.0.0
  page_transition: ^2.0.2
  cherry_toast: ^1.0.0
  syncfusion_flutter_charts:

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.2
  build_runner: ^2.0.6
  analyzer: 1.5.0

flutter:

  uses-material-design: true

  assets:
    - lib/assets/images/
    - lib/assets/images/produto.png

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/icons/lotuserp.ico"
